services:
  database:
    container_name: postgres
    build:
      context: .
      dockerfile: postgres.Dockerfile
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"

